import type { TourDefinition } from './tourTypes.ts'

export const TOURS: Record<string, TourDefinition> = {
  'landing-tour': {
    id: 'landing-tour',
    title: 'AWDAX Platform Tour',
    description: 'A visual walkthrough of how AWDAX turns plain-English data requests into verified datasets.',
    steps: [
      {
        id: 'hero',
        target: '[data-tour="landing-hero"]',
        title: 'Describe Any Data You Need',
        content: 'Type your data goal in plain English. AWDAX understands research intent, discovers relevant web sources, and designs an extraction strategy.',
        tip: 'You can ask for time series, cross-site comparisons, or specific regulatory indicators.',
        badge: 'Start Here',
        stepLabel: 'Beginning',
        placement: 'bottom',
        // Card: inside the highlighted area at bottom-right, shifted further up
        landingCardPosition: 'inside-bottom-right',
        landingCardOffset: { x: -5, y: -45 },
      },
      {
        id: 'liverun',
        target: '[data-tour="landing-liverun"]',
        title: 'Live Source Tracing & Highlighting',
        content: 'Watch AWDAX read live pages. Highlighted values trace directly to your table cell.',
        badge: 'Zero Hallucination',
        stepLabel: 'Live Preview',
        placement: 'top',
        highlightPadding: { bottom: 8, x: 20 },
        // Card: compact 16:9 ratio inside top-right, shifted further right
        landingCardPosition: 'inside-top-right',
        landingCardOffset: { x: 30, y: -20 },
        cardWidth: 380,
      },
      {
        id: 'how',
        target: '[data-tour="landing-how"]',
        title: '5-Step Verified Execution',
        content: 'AWDAX follows a strict workflow: Ask → Plan (you approve) → Run → Review → Use. You stay in control of what URLs get scraped.',
        tip: 'The execution plan is always presented for your approval before scraping begins.',
        badge: 'User Approved',
        placement: 'top',
        // Card: sit inside the highlight area in the empty space at the right center
        landingCardPosition: 'inside-right-center',
      },
      {
        id: 'plan',
        target: '[data-tour="landing-plan"]',
        title: 'You Approve the Execution Plan',
        content: 'Review and approve before scraping starts. Easily edit columns, data types, and target URLs.',
        tip: 'The entire plan editor is fully interactive.',
        badge: 'Zero Risk',
        placement: 'top',
        // Card: inside top-right, shifted a bit up
        landingCardPosition: 'inside-top-right',
        landingCardOffset: { y: -10 },
        cardWidth: 400,
      },
      {
        id: 'receipts',
        target: '[data-tour="landing-receipts"]',
        title: 'Audit Receipts For Every Value',
        content: 'Inspect exact source URLs, HTTP timestamps, and quoted text for any cell.',
        badge: 'Full Traceability',
        placement: 'top',
        // Card: compact 16:9 ratio shifted up
        landingCardPosition: 'inside-top-right',
        landingCardOffset: { y: -20 },
        cardWidth: 380,
      },
      {
        id: 'clean',
        target: '[data-tour="landing-clean"]',
        title: 'Clean by Default & Deduplication',
        content: 'Merges duplicate rows, validates constraints, and flags rejected data.',
        badge: 'Auto Clean',
        placement: 'top',
        // Card: compact 16:9 ratio shifted up and slightly left
        landingCardPosition: 'inside-top-right',
        landingCardOffset: { x: 5, y: -20 },
        cardWidth: 380,
      },
      {
        id: 'dashboards',
        target: '[data-tour="landing-dashboards"]',
        title: 'Instant Dashboards & Auto-Charts',
        content: 'Optimal charts are picked automatically by column type as data streams in.',
        badge: 'Auto Analytics',
        placement: 'top',
        // Card: ultra-compact height in 16:9 ratio, shifted up
        landingCardPosition: 'inside-top-right',
        landingCardOffset: { y: -20 },
        cardWidth: 430,
      },
      {
        id: 'sources',
        target: '[data-tour="landing-sources"]',
        title: 'Permitted & Ethical Sources Only',
        content: 'Respects robots.txt and rate limits, clearly listing skipped sources with reasons.',
        badge: 'Ethical Scraping',
        placement: 'top',
        // Card: compact 16:9 ratio shifted up and slightly left
        landingCardPosition: 'inside-top-right',
        landingCardOffset: { x: 5, y: -20 },
        cardWidth: 380,
      },
      {
        id: 'faq',
        target: '[data-tour="landing-faq"]',
        title: 'Security, Privacy & Export Formats',
        content: 'All data stays local. Export anytime to clean Excel, CSV, JSON-LD, or Markdown.',
        tip: 'Press Escape anytime or use Arrow keys to navigate through tour guides.',
        badge: 'Ready to Explore',
        placement: 'top',
        // Card: inside the highlighted area at bottom-right, shifted a bit down
        landingCardPosition: 'inside-bottom-right',
        landingCardOffset: { y: 25 },
      },
    ],
  },

  'new-chat-tour': {
    id: 'new-chat-tour',
    title: 'New Request & Workspace Tour',
    description: 'Learn how to start a web scrape or drop in your own files for instant visual analysis.',
    steps: [
      {
        id: 'prompt-box',
        target: '[data-tour="new-chat-prompt"]',
        title: 'Natural Language Prompt Box',
        content: 'Describe what dataset or metrics you want to collect. You can type, use voice input, or drop existing CSV/Excel spreadsheets right here.',
        tip: 'Press Enter to submit or click the Send button when ready.',
        badge: 'Prompt Engine',
        placement: 'bottom',
      },
      {
        id: 'shortcuts',
        target: '[data-tour="new-chat-shortcuts"]',
        title: 'Quick Actions & File Tools',
        content: 'One-click shortcuts to upload local spreadsheets, view global projects, or watch simulated sample runs.',
        tip: 'Local files never leave your device—instant private dashboard generation.',
        badge: 'Fast Actions',
        placement: 'top',
      },
      {
        id: 'cards',
        target: '[data-tour="new-chat-cards"]',
        title: 'Curated Templates & Examples',
        content: 'Explore pre-configured examples like monthly automotive metrics, market price comparisons, or custom file visualizers.',
        tip: 'Click "Try" on any card to immediately load its query.',
        badge: 'Templates',
        placement: 'top',
      },
      {
        id: 'refresh-note',
        target: '[data-tour="new-chat-refresh-note"]',
        title: 'Autonomous 5-Min Refresh',
        content: 'Live web scraping requests run continuously in the background, checking sources every 5 minutes and alerting you of new rows.',
        tip: 'You can pause or resume background monitoring at any time from Projects Report.',
        badge: 'Background Sync',
        placement: 'top',
      },
    ],
  },

  'chat-view-tour': {
    id: 'chat-view-tour',
    title: 'Interactive Dashboard & Live Run Tour',
    description: 'Understand live scraping, data inspection, auto-charts, and instant plain-English Q&A.',
    steps: [
      {
        id: 'header',
        target: '[data-tour="chat-header"]',
        title: 'Request Title & Run Status',
        content: 'Displays the goal of this scraping run, live cycle status, and replay or export controls.',
        tip: 'Use the action buttons on the right to replay the run or download the dataset.',
        badge: 'Status',
        placement: 'bottom',
      },
      {
        id: 'thread',
        target: '[data-tour="chat-thread"]',
        title: 'Transparent Strategy & Execution Plan',
        content: 'Review the research phase breakdown, generated queries, and source discovery progress log.',
        tip: 'Every step taken by the AI planner is documented in the thread.',
        badge: 'AI Plan',
        placement: 'bottom',
      },
      {
        id: 'liverun',
        target: '[data-tour="chat-liverun"]',
        title: 'Live Browser & Extraction Strip',
        content: 'Shows live page fetching, active extraction method, and cycle latency.',
        badge: 'Live Scraper',
        placement: 'bottom',
        cardWidth: 350,
        compact: true,
      },
      {
        id: 'data-view',
        target: '[data-tour="chat-data-view"]',
        title: 'Visual Dashboard & Table Views',
        content: 'Switch between Run Report, Data Table, Auto-Charts, and Sources receipts.',
        badge: 'Data Engine',
        placement: 'bottom',
        cardWidth: 360,
        compact: true,
      },
      {
        id: 'ask-box',
        target: '[data-tour="chat-ask-box"]',
        title: 'Ask Questions About The Data',
        content: 'Ask any question about your collected dataset in plain English. Computations and rankings run locally in seconds.',
        badge: 'Instant Q&A',
        placement: 'right',
        cardWidth: 400,
      },
    ],
  },

  'projects-tour': {
    id: 'projects-tour',
    title: 'Projects & Monitoring Report Tour',
    description: 'Master the unified control center for all your live datasets, background monitors, and exports.',
    steps: [
      {
        id: 'kpis',
        target: '[data-tour="projects-kpis"]',
        title: 'Real-Time KPI Metrics',
        content: 'Instant summary of total active projects, currently executing scrapers, continuous background monitors, and total collected rows.',
        tip: 'Numbers update live as background scrapers complete their cycles.',
        badge: 'Overview',
        placement: 'bottom',
      },
      {
        id: 'search-sort',
        target: '[data-tour="projects-search-sort"]',
        title: 'Search & Multi-Column Sorting',
        content: 'Quickly find any dataset by topic keyword, source domain, or error status, and sort by row count, updated time, or creation date.',
        tip: 'Type in the search box to filter across all metadata simultaneously.',
        badge: 'Search',
        placement: 'bottom',
      },
      {
        id: 'filters',
        target: '[data-tour="projects-filters"]',
        title: 'Status Filters & Quick Queries',
        content: 'One-click pills to isolate running jobs, active live-trackers, uploaded spreadsheets, or flagged errors.',
        tip: 'Use Quick queries for instant pre-packaged analytical filters.',
        badge: 'Filters',
        placement: 'bottom',
      },
      {
        id: 'table',
        target: '[data-tour="projects-table"]',
        title: 'Project Data Table & Export Actions',
        content: 'Inspect each project with row counts, current scraping source, live toggle switch, and instant Excel/CSV export.',
        tip: 'Click the Live toggle to pause or resume 5-minute background monitoring for any project.',
        badge: 'Management',
        placement: 'top',
      },
    ],
  },

  'sidebar-tour': {
    id: 'sidebar-tour',
    title: 'Navigation & History Tour',
    description: 'Quickly access new chats, projects reports, searchable history, and user settings.',
    steps: [
      {
        id: 'new-chat-btn',
        target: '[data-tour="workspace-sidebar-new"]',
        title: 'Start a New Request',
        content: 'Click here anytime to start a fresh web data search or drop in a new spreadsheet.',
        tip: 'Shortcut: navigate to /app directly.',
        badge: 'New Request',
        placement: 'right',
      },
      {
        id: 'projects-link',
        target: '[data-tour="workspace-sidebar-projects"]',
        title: 'Projects & Monitoring Dashboard',
        content: 'View all ongoing web scrapers and saved datasets in one consolidated report.',
        tip: 'Check status, error logs, and row totals in real-time.',
        badge: 'Overview',
        placement: 'right',
      },
      {
        id: 'search',
        target: '[data-tour="workspace-sidebar-search"]',
        title: 'Search Chat History',
        content: 'Instantly filter through past queries, scraped tables, and saved chats.',
        tip: 'Searches match both query titles and stored goals.',
        badge: 'Fast Search',
        placement: 'right',
      },
      {
        id: 'history',
        target: '[data-tour="workspace-sidebar-history"]',
        title: 'Past Sessions & Datasets',
        content: 'Revisit any previously generated dashboard. All datasets and charts are preserved.',
        tip: 'Hover over an item to quickly delete or review its details.',
        badge: 'History',
        placement: 'right',
      },
      {
        id: 'account',
        target: '[data-tour="workspace-sidebar-account"]',
        title: 'User Profile & Account',
        content: 'View your signed-in profile details and safely log out of your session.',
        tip: 'Google Auth ensures secure PKCE authentication.',
        badge: 'Account',
        placement: 'top',
      },
    ],
  },
}

export function getTour(id: string): TourDefinition | undefined {
  return TOURS[id]
}
