import type { TourDefinition } from './tourTypes.ts'

export const TOURS: Record<string, TourDefinition> = {
  'landing-tour': {
    id: 'landing-tour',
    title: 'AWDAX Platform Tour',
    description: 'A visual walkthrough of how AWDAX turns plain-English data requests into verified datasets.',
    steps: [
      {
        id: 'hero',
        target: '[data-tour="landing-hero"]',
        title: 'Describe Any Data You Need',
        content: 'Type your data goal in plain English. AWDAX understands research intent, discovers relevant web sources, and designs an extraction strategy.',
        tip: 'You can ask for time series, cross-site comparisons, or specific regulatory indicators.',
        badge: 'Start Here',
        stepLabel: 'Beginning',
        placement: 'bottom',
      },
      {
        id: 'liverun',
        target: '[data-tour="landing-liverun"]',
        title: 'Live Source Tracing & Highlighting',
        content: 'Watch AWDAX read actual web pages in real-time. Values are highlighted in their discovery color and traced directly to the table cell they created.',
        tip: 'Every single number is grounded in real text—no AI hallucinations or fabricated figures.',
        badge: 'Zero Hallucination',
        stepLabel: 'Live Preview',
        placement: 'top',
        highlightPadding: { top: -14, bottom: 8, x: 20 },
      },
      {
        id: 'how',
        target: '[data-tour="landing-how"]',
        title: '5-Step Verified Execution',
        content: 'AWDAX follows a strict workflow: Ask → Plan (you approve) → Run → Review → Use. You stay in control of what URLs get scraped.',
        tip: 'The execution plan is always presented for your approval before scraping begins.',
        badge: 'User Approved',
        placement: 'top',
      },
      {
        id: 'plan',
        target: '[data-tour="landing-plan"]',
        title: 'You Approve the Execution Plan',
        content: 'Nothing runs until you approve the plan. Before AWDAX reads any page, it lists what it will collect and from where—letting you edit columns, types, and sources.',
        tip: 'Every control in this plan editor is interactive—try adding a column or changing extraction methods.',
        badge: 'Zero Risk',
        placement: 'top',
      },
      {
        id: 'receipts',
        target: '[data-tour="landing-receipts"]',
        title: 'Audit Receipts For Every Value',
        content: 'Click any cell in your table to see its exact source URL, HTTP capture timestamp, and the exact sentence quoted from the webpage.',
        tip: 'Export receipts alongside datasets for peer review and compliance audits.',
        badge: 'Full Traceability',
        placement: 'top',
      },
      {
        id: 'clean',
        target: '[data-tour="landing-clean"]',
        title: 'Clean by Default & Deduplication',
        content: 'When multiple sources overlap, AWDAX automatically merges duplicates, validates constraints, and strikes through rejected rows with explicit reasons.',
        tip: 'Disagreements between sources are surfaced clearly so you only review the short exceptions list.',
        badge: 'Auto Clean',
        placement: 'top',
      },
      {
        id: 'dashboards',
        target: '[data-tour="landing-dashboards"]',
        title: 'Instant Dashboards & Auto-Charts',
        content: 'As rows stream in, AWDAX automatically profiles column types, chooses the optimal chart (line, bar, tier distribution), and creates a ready-to-share dashboard.',
        tip: 'Switch views effortlessly between Report, Data Table, Charts, and Source Receipts.',
        badge: 'Auto Analytics',
        placement: 'top',
      },
      {
        id: 'sources',
        target: '[data-tour="landing-sources"]',
        title: 'Permitted & Ethical Sources Only',
        content: 'AWDAX enforces robots.txt rules, respects rate limits, and transparently lists any skipped sources with the exact reason.',
        tip: 'No hidden bypasses or black-box web scraping.',
        badge: 'Ethical Scraping',
        placement: 'top',
      },
      {
        id: 'faq',
        target: '[data-tour="landing-faq"]',
        title: 'Security, Privacy & Export Formats',
        content: 'All uploaded spreadsheets stay in your local browser storage. Export datasets anytime to clean Excel (.xlsx), CSV, JSON-LD, or Markdown tables.',
        tip: 'Press Escape anytime or use Arrow keys to navigate through tour guides.',
        badge: 'Ready to Explore',
        placement: 'top',
      },
    ],
  },

  'new-chat-tour': {
    id: 'new-chat-tour',
    title: 'New Request & Workspace Tour',
    description: 'Learn how to start a web scrape or drop in your own files for instant visual analysis.',
    steps: [
      {
        id: 'prompt-box',
        target: '[data-tour="new-chat-prompt"]',
        title: 'Natural Language Prompt Box',
        content: 'Describe what dataset or metrics you want to collect. You can type, use voice input, or drop existing CSV/Excel spreadsheets right here.',
        tip: 'Press Enter to submit or click the Send button when ready.',
        badge: 'Prompt Engine',
        placement: 'bottom',
      },
      {
        id: 'shortcuts',
        target: '[data-tour="new-chat-shortcuts"]',
        title: 'Quick Actions & File Tools',
        content: 'One-click shortcuts to upload local spreadsheets, view global projects, or watch simulated sample runs.',
        tip: 'Local files never leave your device—instant private dashboard generation.',
        badge: 'Fast Actions',
        placement: 'top',
      },
      {
        id: 'cards',
        target: '[data-tour="new-chat-cards"]',
        title: 'Curated Templates & Examples',
        content: 'Explore pre-configured examples like monthly automotive metrics, market price comparisons, or custom file visualizers.',
        tip: 'Click "Try" on any card to immediately load its query.',
        badge: 'Templates',
        placement: 'top',
      },
      {
        id: 'refresh-note',
        target: '[data-tour="new-chat-refresh-note"]',
        title: 'Autonomous 5-Min Refresh',
        content: 'Live web scraping requests run continuously in the background, checking sources every 5 minutes and alerting you of new rows.',
        tip: 'You can pause or resume background monitoring at any time from Projects Report.',
        badge: 'Background Sync',
        placement: 'top',
      },
    ],
  },

  'chat-view-tour': {
    id: 'chat-view-tour',
    title: 'Interactive Dashboard & Live Run Tour',
    description: 'Understand live scraping, data inspection, auto-charts, and instant plain-English Q&A.',
    steps: [
      {
        id: 'header',
        target: '[data-tour="chat-header"]',
        title: 'Request Title & Run Status',
        content: 'Displays the goal of this scraping run, live cycle status, and replay or export controls.',
        tip: 'Use the action buttons on the right to replay the run or download the dataset.',
        badge: 'Status',
        placement: 'bottom',
      },
      {
        id: 'thread',
        target: '[data-tour="chat-thread"]',
        title: 'Transparent Strategy & Execution Plan',
        content: 'Review the research phase breakdown, generated queries, and source discovery progress log.',
        tip: 'Every step taken by the AI planner is documented in the thread.',
        badge: 'AI Plan',
        placement: 'bottom',
      },
      {
        id: 'liverun',
        target: '[data-tour="chat-liverun"]',
        title: 'Live Browser & Extraction Strip',
        content: 'Shows which web page is currently being fetched, active method (HTML / Structured / Rendered / AI), and latency.',
        tip: 'Click the source chips to see detailed extraction receipts.',
        badge: 'Live Scraper',
        placement: 'bottom',
      },
      {
        id: 'data-view',
        target: '[data-tour="chat-data-view"]',
        title: 'Visual Dashboard & Table Views',
        content: 'Seamlessly switch between summary Run Report, full Data Table, Auto-Generated Charts, and Sources receipts.',
        tip: 'Click any column header to sort or filter rows dynamically.',
        badge: 'Data Engine',
        placement: 'top',
      },
      {
        id: 'ask-box',
        target: '[data-tour="chat-ask-box"]',
        title: 'Ask Questions About The Data',
        content: 'Ask any question about your collected dataset in plain English. Computations (sums, averages, top performers) run locally in seconds.',
        tip: 'Try asking "What is the average value?" or "Which source contributed the most rows?".',
        badge: 'Instant Q&A',
        placement: 'top',
      },
    ],
  },

  'projects-tour': {
    id: 'projects-tour',
    title: 'Projects & Monitoring Report Tour',
    description: 'Master the unified control center for all your live datasets, background monitors, and exports.',
    steps: [
      {
        id: 'kpis',
        target: '[data-tour="projects-kpis"]',
        title: 'Real-Time KPI Metrics',
        content: 'Instant summary of total active projects, currently executing scrapers, continuous background monitors, and total collected rows.',
        tip: 'Numbers update live as background scrapers complete their cycles.',
        badge: 'Overview',
        placement: 'bottom',
      },
      {
        id: 'search-sort',
        target: '[data-tour="projects-search-sort"]',
        title: 'Search & Multi-Column Sorting',
        content: 'Quickly find any dataset by topic keyword, source domain, or error status, and sort by row count, updated time, or creation date.',
        tip: 'Type in the search box to filter across all metadata simultaneously.',
        badge: 'Search',
        placement: 'bottom',
      },
      {
        id: 'filters',
        target: '[data-tour="projects-filters"]',
        title: 'Status Filters & Quick Queries',
        content: 'One-click pills to isolate running jobs, active live-trackers, uploaded spreadsheets, or flagged errors.',
        tip: 'Use Quick queries for instant pre-packaged analytical filters.',
        badge: 'Filters',
        placement: 'bottom',
      },
      {
        id: 'table',
        target: '[data-tour="projects-table"]',
        title: 'Project Data Table & Export Actions',
        content: 'Inspect each project with row counts, current scraping source, live toggle switch, and instant Excel/CSV export.',
        tip: 'Click the Live toggle to pause or resume 5-minute background monitoring for any project.',
        badge: 'Management',
        placement: 'top',
      },
    ],
  },

  'sidebar-tour': {
    id: 'sidebar-tour',
    title: 'Navigation & History Tour',
    description: 'Quickly access new chats, projects reports, searchable history, and user settings.',
    steps: [
      {
        id: 'new-chat-btn',
        target: '[data-tour="workspace-sidebar-new"]',
        title: 'Start a New Request',
        content: 'Click here anytime to start a fresh web data search or drop in a new spreadsheet.',
        tip: 'Shortcut: navigate to /app directly.',
        badge: 'New Request',
        placement: 'right',
      },
      {
        id: 'projects-link',
        target: '[data-tour="workspace-sidebar-projects"]',
        title: 'Projects & Monitoring Dashboard',
        content: 'View all ongoing web scrapers and saved datasets in one consolidated report.',
        tip: 'Check status, error logs, and row totals in real-time.',
        badge: 'Overview',
        placement: 'right',
      },
      {
        id: 'search',
        target: '[data-tour="workspace-sidebar-search"]',
        title: 'Search Chat History',
        content: 'Instantly filter through past queries, scraped tables, and saved chats.',
        tip: 'Searches match both query titles and stored goals.',
        badge: 'Fast Search',
        placement: 'right',
      },
      {
        id: 'history',
        target: '[data-tour="workspace-sidebar-history"]',
        title: 'Past Sessions & Datasets',
        content: 'Revisit any previously generated dashboard. All datasets and charts are preserved.',
        tip: 'Hover over an item to quickly delete or review its details.',
        badge: 'History',
        placement: 'right',
      },
      {
        id: 'account',
        target: '[data-tour="workspace-sidebar-account"]',
        title: 'User Profile & Account',
        content: 'View your signed-in profile details and safely log out of your session.',
        tip: 'Google Auth ensures secure PKCE authentication.',
        badge: 'Account',
        placement: 'top',
      },
    ],
  },
}

export function getTour(id: string): TourDefinition | undefined {
  return TOURS[id]
}
