import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { test } from 'node:test'
import type { DatasetTable } from '../api/types.ts'
import { runQuery } from './aggregate.ts'
import type { Filter, Query } from './aggregate.ts'
import { toNumber } from './decimal.ts'
import { groupKey, profileTable } from './profile.ts'

/**
 * The server answers questions about a table with its own engine (query_engine.py). This runs the browser's engine on the
 * same table and checks the same independently computed answers, so the two can't drift apart. The fixture is generated by
 * tests/fixtures/make_ask_math.py at the repo root.
 */
type PlanFilter = { column?: string; op: Filter['op']; values: string[] }
type Plan = { agg: Query['agg']; measure?: string; groupBy?: string; sort?: Query['sort']; limit?: number; filters?: PlanFilter[] }
type Case = { question: string; plan: Plan; expect: { rows: [string, number | null, number][]; overall: number | null; used: number; matched: number } }

const fixture = JSON.parse(readFileSync(new URL('../../../tests/fixtures/ask_math.json', import.meta.url), 'utf8')) as {
  columns: string[]
  rows: string[][]
  cases: Case[]
}
const profile = profileTable({ columns: fixture.columns, rows: fixture.rows, row_count: fixture.rows.length, records: [] } as unknown as DatasetTable)
const at = (name: string) => {
  const i = profile.columns.findIndex((c) => c.name === name)
  assert.ok(i >= 0, `no column ${name}`)
  return i
}

function toQuery(plan: Plan): Query {
  return {
    agg: plan.agg,
    ...(plan.measure ? { measure: at(plan.measure) } : {}),
    ...(plan.groupBy ? { groupBy: at(plan.groupBy) } : {}),
    ...(plan.sort ? { sort: plan.sort } : {}),
    ...(plan.limit ? { limit: plan.limit } : {}),
    filters: (plan.filters ?? []).map((f) => ({
      column: f.column ? at(f.column) : 0,
      op: f.op,
      // the browser compares "in" values as group keys (toEngineQuery does this for a planned query)
      values: f.op === 'in' || f.op === 'notIn' ? f.values.map(groupKey) : f.values,
    })),
  }
}

test('the columns are read as the server reads them', () => {
  const kinds = Object.fromEntries(profile.columns.map((c) => [c.name, c.kind]))
  assert.deepEqual(kinds, {
    name: 'text', category: 'category', price: 'money', range_km: 'number', rating: 'number',
    reviews: 'number', discount: 'percent', website: 'url', phone: 'text',
  })
})

for (const c of fixture.cases) {
  test(`browser engine: ${c.question}`, () => {
    const result = runQuery(profile, toQuery(c.plan))
    assert.equal(result.stale, false)
    assert.deepEqual(
      result.rows.map((r) => r.label),
      c.expect.rows.map((r) => r[0]),
      'groups and their order',
    )
    result.rows.forEach((r, i) => {
      const [label, value, count] = c.expect.rows[i]
      assert.ok(Math.abs((r.value ? toNumber(r.value) : NaN) - (value as number)) < 1e-9, `${label}: ${r.value ? toNumber(r.value) : null} != ${value}`)
      assert.equal(r.count, count, `${label}: rows in the group`)
    })
    assert.ok(Math.abs((result.overall ? toNumber(result.overall) : NaN) - (c.expect.overall as number)) < 1e-9, 'overall')
    assert.equal(result.used, c.expect.used)
    assert.equal(result.matched, c.expect.matched)
  })
}
